### ISSUE TITLE
failed to run graph-cli

### ISSUE THREAD

**Issue by WJHPrince** [mcastorina/graph-cli#19]
I added the data from `sine.csv` into my `test.csv` and i tried to run 
```bash
graph test.csv -o test.png
```
[ I have installed the graph-cli from pip3 already. ]
But i find out it continously informing me this:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/graph", line 11, in <module>
    sys.exit(main.main())
  File "/usr/local/lib/python3.7/site-packages/graph_cli/main.py", line 8, in main
    args = options.parse_args()
  File "/usr/local/lib/python3.7/site-packages/graph_cli/options.py", line 316, in parse_args
    return validate_args(parser.parse_args())
  File "/usr/local/lib/python3.7/site-packages/graph_cli/options.py", line 60, in validate_args
    fill_global_args(args)
  File "/usr/local/lib/python3.7/site-packages/graph_cli/options.py", line 201, in fill_global_args
    for i in range(len(args.text)):
TypeError: object of type 'NoneType' has no len()
```
Any solutions?

**Comment by mcastorina** [comment]
Thanks for bringing this to my attention! Looks like I didn't completely test out the `--text` option before adding it in. 

The problem was that it loops through all the `--text` flags provided, but I didn't consider the case of none `--text` flags (which results in the arg being `None`).

The fix has been pushed in v0.0.9.
