### ISSUE TITLE
failed to import any qt binding

### ISSUE THREAD

**Issue by zachvalenta** [mcastorina/graph-cli#24]
Seems like the same phenomenon as #22. 

```
(venv) $ graph samples/bar.csv --bar
Traceback (most recent call last):
  File "/Users/zach/Desktop/graph-cli/venv/bin/graph", line 10, in <module>
    sys.exit(main.main())
  File "/Users/zach/Desktop/graph-cli/venv/lib/python3.6/site-packages/graph_cli/main.py", line 17, in main
    create_graph(graphs)
  File "/Users/zach/Desktop/graph-cli/venv/lib/python3.6/site-packages/graph_cli/graph.py", line 218, in create_graph
    import matplotlib.pyplot as plt
  File "/Users/zach/Desktop/graph-cli/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2355, in <module>
    switch_backend(rcParams["backend"])
  File "/Users/zach/Desktop/graph-cli/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/zach/Desktop/graph-cli/venv/lib/python3.6/site-packages/matplotlib/backends/backend_qt4agg.py", line 5, in <module>
    from .backend_qt5agg import (
  File "/Users/zach/Desktop/graph-cli/venv/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "/Users/zach/Desktop/graph-cli/venv/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 15, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/Users/zach/Desktop/graph-cli/venv/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 13, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "/Users/zach/Desktop/graph-cli/venv/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 158, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding

(venv) $ python --version
Python 3.6.1
```

**Comment by ag91** [comment]
I fell into this as well XD
I suspect that M1 Mac users will see this (at least more often): https://stackoverflow.com/questions/70936664/metadata-generation-failed-while-installing-pyqt5

Apparently for that architecture you just need to hide your pyqt5 behind the building magic of homebrew, which takes care of Python 3 issues with the M1 architecture.

So install python3 with brew and then run:
`brew install pyqt5`

Probably this has nothing to do with @mcastorina great work :)
