### ISSUE TITLE
option ‘--help’ fails~

### ISSUE THREAD

**Issue by leafonsword** [mcastorina/graph-cli#26]
Python 3.7 option ‘--help’ has such error:

```
14:36 $ graph --help
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/graph", line 10, in <module>
    sys.exit(main.main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/graph_cli/main.py", line 8, in main
    args = options.parse_args()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/graph_cli/options.py", line 373, in parse_args
    return validate_args(parser.parse_args())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1749, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1781, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1987, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1927, in consume_optional
    take_action(action, args, option_string)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1855, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1037, in __call__
    parser.print_help()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 2474, in print_help
    self._print_message(self.format_help(), file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 2458, in format_help
    return formatter.format_help()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 284, in format_help
    help = self._root_section.format_help()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 525, in _format_action
    help_text = self._expand_help(action)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 614, in _expand_help
    return self._get_help_string(action) % params
ValueError: incomplete format
```

**Comment by mcastorina** [comment]
Fixed in cfae95e8020dc5bc3fe917483be03edf351c220e
