### ISSUE TITLE
error running script in a non-tty environment

### ISSUE THREAD

**Issue by hirani89** [mcastorina/graph-cli#32]
Hi I get an error when I try to run the command.

Here is what I am running `graph /var/www/html/graph-cli/samples/sine.csv -o /var/www/html/graphdemo/public/sine1.png`

and here is what I get

```
Traceback (most recent call last): File "/usr/local/bin/graph", line 11, in sys.exit(main.main()) File "/usr/local/lib/python2.7/dist-packages/graph_cli/main.py", line 10, in main graphs = get_graph_defs(args) File "/usr/local/lib/python2.7/dist-packages/graph_cli/graph.py", line 171, in get_graph_defs graphs, globals = read_chain(args) File "/usr/local/lib/python2.7/dist-packages/graph_cli/graph.py", line 194, in read_chain chain = pickle.loads(getattr(stdin, 'buffer', stdin).read()) File "/usr/lib/python2.7/pickle.py", line 1388, in loads return Unpickler(file).load() File "/usr/lib/python2.7/pickle.py", line 864, in load dispatch[key](self) File "/usr/lib/python2.7/pickle.py", line 886, in load_eof raise EOFError EOFError
```

**Comment by hirani89** [comment]
Looks like i am getting some where. No the error is 

```
Traceback (most recent call last): File "/usr/local/bin/graph", line 7, in from graph_cli import main ModuleNotFoundError: No module named 'graph_cli'
```

**Comment by mcastorina** [comment]
Hi -- a few questions to debug:

1. How did you install graph-cli?
2. What version of Python are you using?

**Comment by hirani89** [comment]
`python3 -m pip install graph-cli` version 3.6

I have been playing around with the way I run it. The error I now get is 
```
Traceback (most recent call last): File "/usr/local/bin/graph", line 11, in sys.exit(main.main()) File "/home/ubuntu/.local/lib/python3.6/site-packages/graph_cli/main.py", line 10, in main graphs = get_graph_defs(args) File "/home/ubuntu/.local/lib/python3.6/site-packages/graph_cli/graph.py", line 171, in get_graph_defs graphs, globals = read_chain(args) File "/home/ubuntu/.local/lib/python3.6/site-packages/graph_cli/graph.py", line 194, in read_chain chain = pickle.loads(getattr(stdin, 'buffer', stdin).read()) EOFError: Ran out of input
```

**Comment by mcastorina** [comment]
How are you running it? Please provide the command you run with the error it gives. This will help me recreate / confirm the bug.

**Comment by hirani89** [comment]
Hi, I am running it from a php script. Using `shell_exec`. All other commands seem to work fine using `shell_exec`. I was also able to install graph-cli using this method. But running it does not work. If I run it from the shell, it works fine though.
`graph /var/www/html/graph-cli/samples/sine.csv -o /var/www/html/site/public/sine1.png`

**Comment by mcastorina** [comment]
Works fine for me.

```php
<?php

shell_exec('graph /tmp/graph-cli/samples/sine.csv -o /tmp/www/sine.png');

?>
```

```
/tmp/www » ls
sine.csv  test.php
/tmp/www » php test.php
/tmp/www » ls
sine.csv  sine.png  test.php
```

Maybe you are experiencing permission issues or some other php-specific problem.

**Comment by mcastorina** [comment]
Also, be sure you do not have multiple versions installed at the same time. I noticed your first error is from python2.7 then another error was python3.6.

Both errors you posted seem to both stem from graph chaining (or the `-C` option).. could that be happening from something else in your `shell_exec` command?

**Comment by hirani89** [comment]
Previously I had python2.7. I removed that and I'm now using python3 by default.

**Comment by hirani89** [comment]
This is what my php looks like
```
echo shell_exec('pwd');
echo shell_exec('whoami');
echo shell_exec('which graph');
echo shell_exec('graph /var/www/html/graph-cli/samples/sine.csv -o /var/www/html/graphdemo/publics/sine1.png 2>&1');
```
and this is the output
```
/var/www/html/test
ubuntu
/usr/bin/graph
Traceback (most recent call last): File "/usr/bin/graph", line 11, in sys.exit(main.main()) File "/home/ubuntu/.local/lib/python3.6/site-packages/graph_cli/main.py", line 10, in main graphs = get_graph_defs(args) File "/home/ubuntu/.local/lib/python3.6/site-packages/graph_cli/graph.py", line 171, in get_graph_defs graphs, globals = read_chain(args) File "/home/ubuntu/.local/lib/python3.6/site-packages/graph_cli/graph.py", line 194, in read_chain chain = pickle.loads(getattr(stdin, 'buffer', stdin).read()) EOFError: Ran out of input
```
Did you make any permission changes to apache or the graph executable?

The only change I made was to run apache under the ubuntu user. but even using www-data user does the same thing.

**Comment by hirani89** [comment]
By the way how did you run the php? from cli or the browser. Mine works from cli but not the browser.

**Comment by mcastorina** [comment]
Thank you for all of the details. I think the problem is from here:
https://github.com/mcastorina/graph-cli/blob/master/graph_cli/graph_cli/graph.py#L192-L194

If stdin is not a tty then it tries to read in data. This explains the weird behavior of it working only in the terminal but not browser.

**Comment by mcastorina** [comment]
Minimal recreation:
```
</dev/null graph sine.csv -o sine.png
```
```
Traceback (most recent call last):
  File "/usr/bin/graph", line 10, in <module>
    sys.exit(main.main())
  File "/usr/lib/python3.7/site-packages/graph_cli/main.py", line 10, in main
    graphs = get_graph_defs(args)
  File "/usr/lib/python3.7/site-packages/graph_cli/graph.py", line 171, in get_graph_defs
    graphs, globals = read_chain(args)
  File "/usr/lib/python3.7/site-packages/graph_cli/graph.py", line 194, in read_chain
    chain = pickle.loads(getattr(stdin, 'buffer', stdin).read())
EOFError: Ran out of input
```

Related bug (closed stdin fd):
```
<&- graph sine.csv -o sine.png
```
```
Traceback (most recent call last):
  File "/usr/bin/graph", line 10, in <module>
    sys.exit(main.main())
  File "/usr/lib/python3.7/site-packages/graph_cli/main.py", line 10, in main
    graphs = get_graph_defs(args)
  File "/usr/lib/python3.7/site-packages/graph_cli/graph.py", line 171, in get_graph_defs
    graphs, globals = read_chain(args)
  File "/usr/lib/python3.7/site-packages/graph_cli/graph.py", line 193, in read_chain
    if not stdin.isatty() and args.file != stdin:
AttributeError: 'NoneType' object has no attribute 'isatty'
```

**Comment by mcastorina** [comment]
Fixed is version 0.1.7

```
python3 -m pip install graph-cli --upgrade
```

**Comment by UdayPad** [comment]
Dear MIccah,

Case-1
----------
When I am running the command from the command line:

 sudo /var/www/html/graph-cli/graph /var/www/html/graph-cli/samples/sine.csv -o /var/www/html/graph-cli/sine92.png

It shows me follow error:

Traceback (most recent call last):
  File "/var/www/html/graph-cli/graph", line 5, in <module>
    import options
ImportError: No module named options

When I do
echo $PATH

it shows me:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/var/www/html/graph-cli

which means that graph cli is there inside my PATH

Case-2
---------
When I am using the same command from my Laravel Controller and then running the route in browser then in browser I do not see any error. And when I run this command:

cat /var/log/apache2/error.log 

I see following error:

sudo: no tty present and no askpass program specified

So I think there are 2 hurdles:

a) Path issue when running the script in command line outside of the directory in which the graph-cli is installed
b) Permission issue (most probably) where no tty present is being displayed.

Kindly help.

**Comment by mcastorina** [comment]
@UdayPad 
a) Please install graph-cli via pip. The `graph` executable was for local development only and has since been removed from the repo.

```
python3 -m pip install graph-cli
```

b) The error you posted is from sudo. The user executing `sudo ...` needs to input a password, but there is no tty or askpass program to do so. You can fix this by adding `NOPASSWD` for that user in the sudoers file. See [this article](https://www.tecmint.com/run-sudo-command-without-password-linux/) for help

**Comment by dibs439** [comment]
Hello Miccah,

Install graph-cli after deleting the previous one.. fresh install. Then ran 
python3 -m pip install graph-cli

But graph command did not appear in the root

Tried running simple command 

graph samples/sine.csv -o sine.png

I see following output


Command 'graph' not found, but can be installed with:

sudo apt install plotutils

What mistake did I make? Please help.

**Comment by dibs439** [comment]
I uninstalled graph-cli 

pip3 uninstall graph-cli

Then installed graph-cli again

python3 -m pip install graph-cli

And after successfull install (no errors at all)

Then I ran 

graph samples/sine.csv -o sine.png

I got this error:

-bash: /usr/bin/graph: No such file or directory

What went wrong, please.
