### ISSUE TITLE
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2

### ISSUE THREAD

**Issue by nodecentral** [mcastorina/graph-cli#40]
Hi

When running a graph command, I’m getting the following error message.. 
````
pi@raspberrypi:/ $ graph home/pi/shared/feed.csv -y 9,10 --style='-.' --ylabel Temp --title CabinTemp --figsize 1600x1000 --output home/pi/shared/cabin_temp_graph.png
Traceback (most recent call last):
  File "/usr/local/bin/graph", line 11, in <module>
    sys.exit(main.main())
  File "/usr/local/lib/python2.7/dist-packages/graph_cli/main.py", line 8, in main
    args = options.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/graph_cli/options.py", line 375, in parse_args
    return validate_args(parser.parse_args())
  File "/usr/local/lib/python2.7/dist-packages/graph_cli/options.py", line 39, in validate_args
    df = pd.read_csv(args.file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1995, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 899, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 914, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 968, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 955, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2172, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2
````

Any ideas how to fix it ?

**Comment by mcastorina** [comment]
The error message appears to be from a malformed CSV file. Can you share the file you are trying to graph?

**Comment by nodecentral** [comment]
Thanks so much, that was exactly it.

I’ve been using a curl command to retrieve the .csv file e.g.
````
curl -o mnt/nas/feed.csv https://api.thingspeak.com/channels/123456/feed.csv?api_key=MYKEY!123&days=7  
````
and for some reason it had an error, and instead of the values being placed into a .csv file,  it created a .csv with the error message in.

**Comment by mcastorina** [comment]
Yes, that's a great idea. Frankly all error handling (or lack of) needs improvement. I've added "invalid CSV file" to #13
